---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    name: traefik
    ## @param module labels for the deployed component
    ##   app.kubernetes.io/component (architecture level): <<name of implemented via>> (see https://www.notion.so/cybnity/5a681e57f2164d4f8a3f228129294db9?v=348e6a0d04e449f883616c948abec85d) as ui, application, domain, infrastructure, security-control
    ##   app.kubernetes.io/part-of (application level): <<name of deploybale system>> (see https://cybnity.notion.site/5a681e57f2164d4f8a3f228129294db9?v=02fde7cb6f8e4d69b8497d6ca97e4316); for e.g. Asset Control Domain Gateway
    ##
    app.kubernetes.io/component: infrastructure
  annotations:
    helm.sh/resource-policy: keep
