annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.1.0

# @Requirement(reqType = RequirementCategory.Maintainability, reqId = "REQ_MAIN_1")
description: CYBNITY defense platform chart for Kubernetes

#home: https://github.com/bitnami/charts/tree/main/bitnami/kafka
#icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
- cybnity-platform

maintainers:
- name: CYBNITY
  url: https://github.com/cybnity/iac-helm-charts
name: cybnity-platform
#sources:
#- https://github.com/bitnami/containers/tree/main/bitnami/kafka
#- https://kafka.apache.org/
version: 1.0.0
