# THIS CHART IS AN UMBRELLA CHART  of all infrastructure and application components required to build and deployment a full cybnity environment
apiVersion: v2
name: cybnity-platform # Chart name
version: 1.0.0 # SemVer 2 Chart version
icon: https://github.com/cybnity/foundation/blob/main/cybnity-logo.png # Internet accessible URL to icon image, or base64 formatted icon
# @Requirement(reqType = RequirementCategory.Maintainability, reqId = "REQ_MAIN_1")
description: CYBNITY systems packaged and integrated defense platform allowing deployment on Kubernetes cluster.

keywords:
  - cybnity-platform

home: https://hub.docker.com/r/cybnity/cybnity-platform

sources:
  # URLs to source code for the project
  - https://github.com/cybnity/iac-helm-charts/tree/main/cybnity-platform
  - https://github.com/bitnami/charts/tree/main/bitnami/common

dependencies:
  # GENERIC INFRASTRUCTURE MODULES
  - name: domains-interactions-space
    condition: domains-interactions-space.enabled
    version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

  - name: users-interactions-space
    condition: users-interactions-space.enabled
    version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

  - name: knowledge-repository
    condition: knowledge-repository.enabled
    version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

  # APPLICATION MODULES
  #- name: access-control-sso
  #  condition: access-control-sso.enabled
  #  version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

  # Project description (see https://artifacthub.io/packages/helm/bitnami/keycloak)
  - name: keycloak # Origin Keycloak Chart.yaml name
    version: "25.2.0" # Chart.yaml SemVer 2 version. Chart version "21.4.4" # Keycloak project documentation at https://github.com/bitnami/charts/tree/main/bitnami/keycloak
    repository: oci://registry-1.docker.io/bitnamicharts # URL of the Bitnami legacy repository (non production only) publicly stored on DockerHub
    condition: keycloak.enabled
    alias: access-control-sso ## access-control-sso extended name usable into custom cybnity-platform templates in place of keycloak default name for access to keycloak project attributes via logical name different than keycloak implementation name (for e.g. .Values.access_control_sso.<<value_name>>

  - name: reactive-messaging-gateway
    condition: reactive-messaging-gateway.enabled
    version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

  - name: web-reactive-frontend
    condition: web-reactive-frontend.enabled
    version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

  - name: ui-apis-gateway
    condition: ui-apis-gateway.enabled
    version: ">=1.0.0" # dependency Chart.yaml SemVer 2 version

maintainers: # Referent maintainers of this Helm project
  - name: CYBNITY team
    email: olivier@cybnity.org
    url: https://github.com/cybnity/iac-helm-charts

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

appVersion: "1.0.0" # Version of the defense integrated solution that this project contains

annotations:
  category: Solution
  licenses: Apache-2.0
