# Values regarding ALPHA version of cybnity-platform packaged systems.
# The ALPHA version of cybnity-platform is based on latest unstable versions of application components that are currently eligible for deploymnent into a automated acceptance test stage environment.

# It's including application components (Docker containerized application components), technical components (e.g integration middleware systems, data storage systems) and infrastructure resources (e.g Kubernetes services, network components, configuration objects).

# ALPHA version: this packaged solution version SHALL NOT BE USED IN PRODUCTION because without any guaranted integration acceptance (transversal compatibility integration tests not performed), user acceptance (end-to-end usage scenation tests not performed) or quality compliance (components quality and security tests not performed).

# This is a YAML-formatted file, that define variables to be passed into the templates.

## Enable diagnostic mode in the statefulset
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers in the statefulset
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers in the statefulset
  ##
  args:
    - infinity

# values authorized: keep, delete
helmResourcePolicy: delete

## ---------------

## --- KUBERNETES TEMPLATES values ---

### Namespace objects configuration
namespaces:
  - cybnity-system
  # To support cert-manager
  - cert-manager

annotations:
  certmanager.k8s.io/disable-validation: "true"

namespace:
  labels: {}
   #  additional_label1: myvalue

## ---------------

## --- DEFAULT PROFILING OF SUB-PROJECTS regarding cybnity-platform infrastructure modules deployed ---
## Custom redefined value according to the version deployed of application systems

### domains-interactions-space:
#kafka:

### users-interactions-space:
# redis:
    ## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
    ##
#   architecture: standalone # limitation to unique master instance by default

### knowledge-repository:
janusgraph:
  ## @param replicaCount Number of Graph server replicas to deploy
  ##
  replicaCount: 1
  #cassandra:

### access-control-sso
keycloak:
    ## @param replicaCount Number of Keycloak replicas to deploy
    ##
    replicaCount: 3

## ---------------

## --- DEFAULT PROFILING OF SUB-PROJECTS regarding cybnity-platform application modules deployed ---

### reactive-messaging-gateway:

### web-reactive-frontend:

### ui-apis-gateway
#cert-manager:
#haproxy:

## ---------------
