# When Helm reads this template, it will simply send it to Kubernetes as-is
# In Kubernetes, a ConfigMap is simply an object for storing configuration data. Other things, like pods, can access the data in a ConfigMap.

apiVersion: v1
kind: ConfigMap
metadata:
  name: cybnity-configmap
data:
  myvalue: "Hello World"
