apiVersion: v2
name: access-control-sso
version: 1.0.0  # SemVer 2 version
# @Requirement(reqType = RequirementCategory.Maintainability, reqId = "REQ_MAIN_1")
description: CYBNITY identity and access management server.

type: application

sources:
  # URLs to source code for the project
  - https://github.com/cybnity/iac-helm-charts/tree/main/cybnity-platform/charts/access-control-sso

# list of sub-chart required by module
dependencies:
  # Project description (see https://artifacthub.io/packages/helm/bitnami/keycloak)
  - name: keycloak
    version: "25.2.0" # Free ArtifactHub repo at https://artifacthub.io/packages/helm/bitnami/keycloak
    # Chart version "21.4.4" # Keycloak project documentation at https://github.com/bitnami/charts/tree/main/bitnami/keycloak
    repository: oci://registry-1.docker.io/bitnamicharts # URL of the Bitnami legacy repository (non production only) publicly stored on DockerHub

appVersion: "1.0.0" # Version of the app that this project contains

annotations:
  category: Infrastructure
  licenses: Apache-2.0
