# Customization of the default values for cert-manager

#cert-manager: #defined by either the name or alias of your dependency in Chart.yaml
#  namespace: security

# IMAGE VERSION SUPPORTED BY THE CustomResourceDefinition created into the cluster instance
image.tag: v1.11.1

# ASSIGNMENT TO THE NODE ('layer' label value relative to a cluster area) USING THE CERT-MANAGER
## Node labels for pod assignment
# cybnity.io/domains-io-area: "true"
# cybnity.io/domains-area: "true"
# cybnity.io/user-interfaces-area: "true"
# cybnity.io/infrastructure-services-area: "true"
nodeSelector:
    cybnity.io/user-interfaces-area: "true"

# Labels to add to the cert-manager pod
podLabels:
    type: ui-cert-manager

## Node affinity for pod assignment
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cybnity.io/user-interfaces-area
            operator: In
            values:
            - "true"

## Node labels for webhook pod assignment
webhook.nodeSelector:
   cybnity.io/user-interfaces-area: "true"

## Node affinity for webhook pod assignment in the same area where the cert-manager pod had been deployed
webhook.affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: type
              operator: In
              values:
              - ui-cert-manager

## Node labels for cainjector pod assignment
cainjector.nodeSelector:
    cybnity.io/user-interfaces-area: "true"

## Node affinity for cainjector pod assignment in the same area where the cert-manager pod had been deployed
cainjector.affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: type
              operator: In
              values:
              - ui-cert-manager

## Node labels for startupapicheck pod assignment
startupapicheck.nodeSelector:
    cybnity.io/user-interfaces-area: "true"

## Node affinity for startupapicheck pod assignment in the same area where the cert-manager pod had been deployed
startupapicheck.affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: type
              operator: In
              values:
              - ui-cert-manager
