## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.defaultStorageClass Global default StorageClass for Persistent Volume(s)
##

global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  defaultStorageClass: ""
  ## Security parameters
  ##
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: false

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

traefik:
  enabled: false # None automated installation of Traefik by API project

# CONFIGURATION OF HTTPROUTE created by Helm templates and managed by Traefik Gateway API
# Doc about reverse proxy at https://github.com/keycloak/keycloak/blob/main/docs/guides/server/reverseproxy.adoc
httproutes: []

# CONFIGURATION OF INGRESS ROUTE LINKED TO EXPOSED HTTP ROUTES
ingressroutes: []

# CONFIGURATION OF FILTER APPLICABLE TO HTTP ROUTES
middlewares:
  secureHeaders:
    name: secure-headers
    namespace: default
  ipAllowlist:
    name: ip-allowlist
    namespace: default
    sourceRange:
      - 127.0.0.1/32 # Cluster server common loop ip address range
      - 10.0.0.0/16  # Typical cluster network range
      - 192.168.0.0/24  # Common local network range

#resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
