## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.defaultStorageClass Global default StorageClass for Persistent Volume(s)
##

global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  defaultStorageClass: ""
  ## Security parameters
  ##
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: false

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# CONFIGURATION OF HTTPROUTE created by Helm templates and managed by Traefik Gateway API
# Doc about reverse proxy at https://github.com/keycloak/keycloak/blob/main/docs/guides/server/reverseproxy.adoc
httproutes:
  # Declaration of resources managed via Gateway API
  - serviceName: reactive-backend-system
    namespace: default
    parentRefs:
      - name: traefik-apis-gateway
        #sectionName: http
        #kind: Gateway
    hostnames:
      - reactive-backend-system.cluster.local
    matches:
      - paths:
          # See path required to be exposed for backend api external access
          - type: PathPrefix
            value: /api/
        backendRefs:
          - name: reactive-backend-system
            port: 80
        # Gateway API's native filter mechanism applied rather than annotations
        #filters:
        #  - type: ExtensionRef
        #    extensionRef:  # Headers Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: secure-headers
        #  - type: ExtensionRef
        #    extensionRef: # IP AllowList Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: ip-allowlist
        #      name: ip-allowlist
  - serviceName: web-reactive-frontend-system
    namespace: default
    parentRefs:
      - name: traefik-apis-gateway
        #sectionName: http
        #kind: Gateway
    hostnames:
      - web-reactive-frontend-system.cluster.local
    matches:
      - paths:
          # See path required to be exposed for web ui external access
          - type: PathPrefix
            value: /ui/
        backendRefs:
          - name: web-reactive-frontend-system
            port: 80
        # Gateway API's native filter mechanism applied rather than annotations
        #filters:
        #  - type: ExtensionRef
        #    extensionRef:  # Headers Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: secure-headers
        #  - type: ExtensionRef
        #    extensionRef: # IP AllowList Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: ip-allowlist
        #      name: ip-allowlist
  - serviceName: access-control-sso-system
    namespace: default
    parentRefs:
      - name: traefik-apis-gateway
        #sectionName: http
        #kind: Gateway
    hostnames:
      - access-control-sso.cluster.local
      #- sso.cluster.local
      #- localhost # server name based API (e.g localhost server hostname) or dns name based API (e.g dev.cybnity.tech)
      #- 127.0.0.1 # Ip address based API (e.g 127.0.0.1 ip address of the hosting machine exposing the route endpoint)
    matches:
      - paths:
          # See path required to be exposed for Keycloak interactions
          # https://www.keycloak.org/server/reverseproxy#_exposed_path_recommendations
          # Common Keycloak required paths
          - type: PathPrefix
            value: /realms/
          - type: PathPrefix
            value: /resources/ # This path is needed to serve assets correctly. It may be served from a CDN instead of the {project_name} path.
          - type: PathPrefix
            value: /.well-known/ # This path is needed to resolve Authorization Server Metadata and other information via RFC 8414.
        backendRefs:
          - name: access-control-sso-system
            port: 80
        # Gateway API's native filter mechanism applied rather than annotations
        #filters:
        #  - type: ExtensionRef
        #    extensionRef:  # Headers Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: secure-headers
        #  - type: ExtensionRef
        #    extensionRef: # IP AllowList Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: ip-allowlist
      - paths:
          # Specific administration console path
          - type: PathPrefix # Keycloak administration console exposure (BECAREFULL, AUTHORIZED ONLY FOR DEVELOPMENT)
            value: /admin/
        backendRefs:
          - name: access-control-sso-system
            port: 80
        # Gateway API's native filter mechanism applied rather than annotations
        #filters:
        #  - type: ExtensionRef
        #    extensionRef:  # Headers Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: secure-headers
        #  - type: ExtensionRef
        #    extensionRef: # IP AllowList Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: ip-allowlist
      - paths:
          # Specific frontend authentication web page provided by Keycloak
          - type: PathPrefix
            value: /auth/
        backendRefs:
          - name: access-control-sso-system
            port: 80
        # Gateway API's native filter mechanism applied rather than annotations
        #filters:
        #  - type: ExtensionRef
        #    extensionRef:  # Headers Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: secure-headers
        #  - type: ExtensionRef
        #    extensionRef: # IP AllowList Middleware applied
        #      group: traefik.io
        #      kind: Middleware
        #      name: ip-allowlist

# CONFIGURATION OF INGRESS ROUTE LINKED TO EXPOSED HTTP ROUTES
ingressroutes:
  # Declaration of resource managed via CRD
  - serviceName: web-reactive-frontend-system
    namespace: default
    entryPoints:
      - web
    routes:
      - match: PathPrefix(`/ui`)
        kind: Rule
        # Filter mechanism applied to IngressRoute via middlewares
        #middlewares:
        #  - secure-headers
        #  - ip-allowlist
        services:
          - name: web-reactive-frontend-system
            port: 80
    # Optional tls configuration
    # Doc at https://doc.traefik.io/traefik/expose/kubernetes/advanced/#using-ingressroute-with-lets-encrypt
    #tls:
      # Resolver (certificate resolver name) reference for obtain or renew a certificate about domain declared into the match
      #certResolver: le
  - serviceName: reactive-backend-system
    namespace: default
    entryPoints:
      - web
    routes:
      - match: PathPrefix(`/backend`)
        kind: Rule
        # Filter mechanism applied to IngressRoute via middlewares
        #middlewares:
        #  - secure-headers
        #  - ip-allowlist
        services:
          - name: reactive-backend-system
            port: 80
    # Optional tls configuration
    # Doc at https://doc.traefik.io/traefik/expose/kubernetes/advanced/#using-ingressroute-with-lets-encrypt
    #tls:
      # Resolver (certificate resolver name) reference for obtain or renew a certificate about domain declared into the match
      #certResolver: le
  - serviceName: access-control-sso-system
    namespace: default
    entryPoints:
      - web
    routes:
      - match: PathPrefix(`/auth`) || PathPrefix(`/realms/`) || PathPrefix(`/resources/`) || PathPrefix(`/js/`) # Paths required to be exposed for Keycloak interactions (see https://www.keycloak.org/server/reverseproxy)
        kind: Rule
        # Filter mechanism applied to IngressRoute via middlewares
        #middlewares:
        #  - secure-headers
        #  - ip-allowlist
        services:
          - name: access-control-sso-system
            port: 80
    # Optional tls configuration
    # Doc at https://doc.traefik.io/traefik/expose/kubernetes/advanced/#using-ingressroute-with-lets-encrypt
    #tls:
      # Resolver (certificate resolver name) reference for obtain or renew a certificate about domain declared into the match
      #certResolver: le

# CONFIGURATION OF FILTER APPLICABLE TO HTTP ROUTES
middlewares:
  secureHeaders:
    name: secure-headers
    namespace: default
  ipAllowlist:
    name: ip-allowlist
    namespace: default
    sourceRange:
      - 127.0.0.1/32 # Cluster server common loop ip address range
      - 10.0.0.0/8  # Typical cluster network range
      - 192.168.0.0/24  # Common local network range

#resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
