name: Package & Publish Workflow

on:
  push:
    branches:
      - main
    #paths:
    #  - '**.yaml'
    #  - '**.yml'

jobs:
  package:
    name: Platform Packaging
    # depending on default permission settings for the organization (contents being read-only or read-write for workloads), required to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      PACKAGED_PROJECT: "cybnity-platform"
      # See doc : https://github.com/atomicfi-engineering/action-build-push-chart-oci-registry
      # Path to chart. Required
      CHART_DEST: "packages"
      # Sets whether or not to update dependencies before packaging
      # Default: true
      update-dependencies: true
    outputs:
      chart_path: ${{ env.CHART_PATH }}
      package_version_name:  ${{ env.PACKAGE_VERSION_NAME }}
      
    steps:
      - name: Helm source codes checkout
        id: checkout_step
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm tool
        uses: azure/setup-helm@v3

      - if: ${{ env.update-dependencies }}
        name: Update Chart Dependencies
        shell: bash
        run: |
          helm dependency update ${{ env.PACKAGED_PROJECT }}
          
      - name: Helm Packaging
        run: |
          PACKAGE_VERSION_NAME="0.1.0+$(git rev-parse --short "$GITHUB_SHA")"
          echo "PACKAGE_VERSION_NAME=$PACKAGE_VERSION_NAME" >> $GITHUB_ENV
          helm package ${{ env.PACKAGED_PROJECT }} --version "$PACKAGE_VERSION_NAME" -d ${{ env.CHART_DEST }}
          echo "CHART_PATH=$CHART_DEST/$PACKAGED_PROJECT-$PACKAGE_VERSION_NAME.tgz" >> $GITHUB_ENV
          
  publish:
    name: Repository Publishing
    needs: [package]
    if: success()
    permissions:
      # permits an action to upload and publish packaged files
      contents: write
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_ACCESS_ACCOUNT }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}
      OCI_PATH: ${{ secrets.DOCKERHUB_OLIVIER_PATH }}
      PACKAGED_CHART_PATH: ${{ needs.package.outputs.chart_path }}
      CHART_DEST: ${{ needs.package.env.CHART_DEST }}
      # URL of registry, excluding the protocol. Required.
      registry-url: registry-1.docker.io
      # Repository in registry to push to
      repository: cybnity
      # Username to login to registry
      username: cybnity
      # Password to login to registry
      # password: ${{ secrets.DOCKERHUB_OLIVIER_PATH }}
      # Enables step to delete all `*.tgz` files
      # Default: true
      delete-tgzs: true
    steps:
      - name: Helm Registry Login
        shell: bash
        run: |
          helm registry login \
          --username ${{ env.username }} \
          --password ${{ env.OCI_PATH }} \
          ${{ env.registry-url }}
          
      - name: Push Chart
        shell: bash
        run: |
          cd ${{ env.CHART_DEST }}
          for file in *.tgz; do
            [ -f "$file" ] || continue
            helm push $file oci://${{ env.registry-url }}/${{ env.repository }}
          done
          
      - name: Delete Chart Tarballs
        if: ${{ env.delete-tgzs }} == true
        shell: bash
        run: |
          cd ${{ env.CHART_DEST }}
          for file in *.tgz; do
            [ -f "$file" ] || continue
            rm $file
          done
