name: Platform Charts Build

on:
  push:
    branches:
      - main
    #paths:
    #  - '**.tgz'
    #  - '**.yaml'

jobs:
  package-and-release:
    name: Package & Release
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      # permits an action to upload and publish packaged files into GitHub page branch and to update index.yaml file in pages branche
      contents: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Helm source codes checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm tool
        uses: azure/setup-helm@v3

      - name: Helm Package
        run: helm package cybnity-platform --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d repository

      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          CHART_PACKAGE_NAME="cybnity-platform-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          cd repository
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main:refs/heads/gh-branch
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: repository
          skip_packaging: 'false'
        env:
          CR_TOKEN: ${{ github.token }}
