apiVersion: v2
name: reactive-messaging-gateway
version: 1.0.0  # SemVer 2 version
# @Requirement(reqType = RequirementCategory.Maintainability, reqId = "REQ_MAIN_1")
description: CYBNITY backend server exposing UI capabilities to front end user interface.

type: application

sources:
  # URLs to source code for the project
  - https://github.com/cybnity/iac-helm-charts/tree/main/cybnity-platform/charts/reactive-messaging-gateway

appVersion: "0.1.0" # Version of the app that this project contains
